### PR TITLE
Add plural flag

### PR DESCRIPTION
**Pull request by moehreag**

### CODE REVIEW

**Comment by hexaclue** [comment]
What's the source of the colours? I've been looking but cannot find a single source with these specific colours.

**Comment by moehreag** [comment]
> What's the source of the colours? I've been looking but cannot find a single source with these specific colours.

probably not perfect colors due to being color-picked, but from 
[here](https://github.com/QuiltMC/art/blob/master/misc/patches/pride/patch_plural.svg)

**Comment by hexaclue** [comment]
You seem to be right. The proper colours (as converted to hex from the file you linked) seem to be:
- #31c69e
- #347dde
- #6b3fbd
- #000000

Could you edit your contribution so the right hex codes are in the array?

**Comment by moehreag** [comment]
> You seem to be right. The proper colours (as converted to hex from the file you linked) seem to be:
> 
>     * #31c69e
> 
>     * #347dde
> 
>     * #6b3fbd
> 
>     * #000000
> 
> 
> Could you edit your contribution so the right hex codes are in the array?

Thanks for converting the colors!

**Comment by hexaclue** [comment]
Merged in 451d981b5cf8306a87f0ab5b7166b96fbb028d37

**Pull request closed without merging**
